// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qpgjdaaavbvrejygsopz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwZ2pkYWFhdmJ2cmVqeWdzb3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0ODg3NTcsImV4cCI6MjA3NTA2NDc1N30.HyBxUEKS1mSp5wZcuvb-iMkDO05zTgiJ4Y69G4Fo0pQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);